# Config file:
remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US
title: "Navil-Varta"
description: "Interesting and Effective Stories, News, Theories of ALL with original content"
baseurl: 
url: "navilvarta.ga"
theme_settings :
     favicon : favicon.ico/final.ico
logo: favicon.ico/nv.ico
date_format: "%Y-%m-%d"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-155354311-1"
disqus:
  shortname: "navil-varta"
twitter:
  username: ""
gems:
    - jekyll-seo-tag
    - jekyll-lunr-js-search
    - jekyll-feed
# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination 
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# SiteMap
url: "https://navilvarta.ga" # the base hostname & protocol for your site

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-lunr-js-search

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author: 
  name: MdY
  picture: /assets/getProfileImage.png
  email:
  twitter: https://twitter.com/
  links:
    - title: LinkedIn
      url: https://linkedin.com/in/
      icon:

social:
  name: Mcubes
  links:
    - https://mcubescloud.tk
    

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/mdy007
    icon: fab fa-github-square
copyright: "©2020 All Right Reserved. "
